// Curated internal data-request emails for the free Templates tab. The consultant (or
// the client's sustainability lead) pastes these into their mail client to ask each
// internal team for the BRSR data it owns. Pure + client-safe, plain text (no HTML).
// Personalized with the client name + reporting FY at build time. Deliberately a
// curated 5–8-item ask per team, NOT the full 108-field dump (that's the PDF brief).
//
// This is the free, manual version of what Collect (Pro) automates: branded sending,
// tracking and auto-reminders. The voice mirrors the Collect request email
// (src/lib/datarequest/email.ts): warm, brief, action-oriented.

export interface TeamEmail {
  team: string;        // who this email is for
  chip: string;        // short role chip (mirrors OWNERS chips)
  principles: string[]; // BRSR principles this team covers, for the UI
  intro: string;       // the one-line ask context (after the company/FY line)
  asks: string[];      // the plain-English data points being requested
}

export const TEAM_EMAILS: TeamEmail[] = [
  {
    team: "People / HR",
    chip: "HR / People team",
    principles: ["P3", "P5"],
    intro: "You're best placed to provide the workforce numbers. A few of these come straight from payroll and the HR system:",
    asks: [
      "Headcount: permanent and contract employees and workers, split by gender",
      "Differently-abled employees and workers, split by gender",
      "Wages: how many are paid at or above the applicable minimum wage",
      "Benefits coverage: PF, ESI, gratuity, maternity (% of staff covered)",
      "Training: average training hours per employee, and safety / skill-upgrade coverage",
      "POSH: sexual-harassment complaints filed and resolved this year",
      "Grievances: complaints received and resolved on working conditions",
      "Turnover: hires and exits during the year, by gender",
    ],
  },
  {
    team: "Plant / EHS / Energy",
    chip: "Plant / EHS / Energy",
    principles: ["P6"],
    intro: "These drive the emissions, water and waste figures. Most come from utility bills, meter readings and fuel logs, the source document is enough:",
    asks: [
      "Grid electricity consumed for the year (kWh), and any renewable / captive power",
      "Fuel consumed by type: diesel/HSD (litres), LPG (kg), CNG (m³), coal (kg), furnace oil (litres)",
      "Water withdrawal by source (kL) and total water discharged (kL)",
      "Waste generated by stream: hazardous, plastic, e-waste, other (tonnes), and how it's disposed",
      "Air emissions if monitored: NOx, SOx, PM (kg or tonnes)",
      "Any energy or water audit / external assessment done this year",
    ],
  },
  {
    team: "Company Secretary / Legal",
    chip: "Company Secretary / Legal",
    principles: ["P1", "P5"],
    intro: "These sit in board records and the compliance register. A short note against each is fine:",
    asks: [
      "Board composition: size, independent directors, and women on the board",
      "Anti-corruption / anti-bribery policy, and any disciplinary actions taken",
      "Fines, penalties or settlements during the year (with the brief reason)",
      "Conflict-of-interest disclosures by directors / KMP",
      "Status of policies required under the nine NGRBC principles (in place / approved by board / web-link)",
      "Any pending material legal or regulatory proceedings on responsible-business conduct",
    ],
  },
  {
    team: "Procurement / Product",
    chip: "Procurement / Product",
    principles: ["P2"],
    intro: "These cover sourcing and product responsibility, your purchasing and product records will have them:",
    asks: [
      "Share of inputs sourced sustainably (% of total purchases), with how it's defined",
      "Recycled or reused input material as a share of total material used",
      "Reclaimed products / packaging at end of life (% reclaimed)",
      "EPR (Extended Producer Responsibility) status, and whether the waste-collection plan is on track",
      "Any life-cycle assessments (LCA) conducted on key products",
      "% of value-chain partners assessed on environmental and social parameters",
    ],
  },
  {
    team: "CSR / Community",
    chip: "CSR team",
    principles: ["P8"],
    intro: "These come from CSR spend and project records:",
    asks: [
      "CSR spend for the year (₹), against the prescribed obligation",
      "CSR projects: location, focus area, and beneficiaries reached",
      "Projects in aspirational / backward districts, if any",
      "Preferential procurement from marginalised / vulnerable groups (% of spend)",
      "Any social-impact assessment carried out on CSR projects",
      "Corrective actions taken on community grievances",
    ],
  },
];

// Build the copy-paste email text for one team, personalized with the client + FY.
// Returns a subject line and a plain-text body, ready for the clipboard.
export function buildTeamEmail(t: TeamEmail, opts: { company?: string; fy: string }): { subject: string; body: string } {
  const company = (opts.company || "").trim() || "the client";
  const subject = `Data request for ${company}'s BRSR report, ${t.chip}`;
  const bullets = t.asks.map((a) => `  • ${a}`).join("\n");
  const body =
    `Hi,\n\n` +
    `We're preparing the BRSR (Business Responsibility & Sustainability Report) for ${company} for ${opts.fy}. ` +
    `${t.intro}\n\n` +
    `${bullets}\n\n` +
    `Where a figure comes from a bill, register or meter reading, just attach or point to that, it's what assurance will ask for. ` +
    `For anything you don't track yet, a quick "not available" is enough so we can plan around it.\n\n` +
    `Please share what you can by reply. Thanks for the help.`;
  return { subject, body };
}
